baseURL = 'http://labbaf.net/'
locale = 'en-us'
title = "Sina's Homepage"
theme = "hugo-paper"
publishDir = 'public'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[security]
  allowContent = [".*"]


[pagination]
  pagerSize = 3

[params]
  color = 'linen'
  name = 'Sina Labbaf'
  avatar = 'images/avatar.jpg'
  bio = 'Software Engineer at Google | PhD in Computer Science'
  github = 'laboox'
  linkedin = 'sinalabbaf'
  instagram = 'sameoldsina'


[services]
  [services.googleAnalytics]
    id = 'G-RNKJW15WW2'

[deployment]
  [[deployment.targets]]
    name = "aws"
    URL = "s3://labbaf.net?region=us-west-2"
  [[deployment.targets]]
    name = "gcp"
    URL = "gs://labbaf-net-homepage"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "https://scholar.google.com/citations?user=8SWJZFkAAAAJ"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/zotcare"
    weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
