main:
  - name: About
    url: '#about'
    weight: 1
  - name: Publications
    url: https://scholar.google.com/citations?user=8SWJZFkAAAAJ
    weight: 2
  - name: Projects
    url: /projects/zotcare
    weight: 3
  - name: Blog
    url: /blog/
    weight: 4
